//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordens
    {
        public int id { get; set; }
        public int idcliente { get; set; }
        public string idacao { get; set; }
        public Nullable<System.DateTime> dataordem { get; set; }
        public int quantidadeacao { get; set; }
        public Nullable<System.DateTime> datacompra { get; set; }
        public decimal valorordem { get; set; }
        public decimal taxacorretagem { get; set; }
        public decimal impostorenda { get; set; }
        public string tipoordem { get; set; }
    
        public virtual acoes acoes { get; set; }
        public virtual clientes clientes { get; set; }
    }
}
